### ISSUE TITLE
Migration to Angular 17

### ISSUE THREAD

**Issue by Zahen** [EmmanuelRoux/ngx-matomo#87]
Hi, 

After upgrading my app to Angular 17, Matomo does not track anythings know.

- I am Using : "ngx-matomo-client": "^6.1.3"
- In my app.module.ts : 
```
providers: [
    provideMatomo({trackerUrl: 'http://localhost:9999/', siteId: '1'}, withRouter())
  ],
```
- In my app.component.ts : 
```
readonly tracker = inject(MatomoTracker);
ngOnInit(): void {
  this.messageService.titleChanges().subscribe({
    next: title => this.tracker.trackPageView(title),
    error: err => this.messageService.handleError(err)
  })
}
```
- My docker-compose for my matomo server:
```
version: '3.7'

services:
  app:
    image: matomo:5.0.3
    restart: unless-stopped
    volumes:
      - ./data:/var/www/html:z
    environment:
      MATOMO_DATABASE_HOST: db
    ports:
      - 9999:80
    depends_on:
      - db

  db:
    image: mariadb:11.1.2
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - ./db:/var/lib/mysql:z
    env_file:
      - matomo.env

```

For your information, on Angular 15, I have ngx-matomo-client : 5.0.1, and it worked fine.

Thank you for your help.
